/// Model for one of the 99 Names of Allah
class NameOfAllah {
  final int number;
  final String arabic;
  final String transliteration;
  final String meaning;
  final String description;

  const NameOfAllah({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.meaning,
    required this.description,
  });
}

/// Service providing the 99 Names of Allah (Asma ul Husna)
class NamesOfAllahService {
  static final NamesOfAllahService _instance = NamesOfAllahService._internal();
  factory NamesOfAllahService() => _instance;
  NamesOfAllahService._internal();

  /// The 99 Beautiful Names of Allah
  static const List<NameOfAllah> names = [
    NameOfAllah(
      number: 1,
      arabic: 'الرَّحْمَنُ',
      transliteration: 'Ar-Rahman',
      meaning: 'The Most Gracious',
      description: 'The One who has plenty of mercy for the believers and the disbelievers in this world and the Hereafter.',
    ),
    NameOfAllah(
      number: 2,
      arabic: 'الرَّحِيمُ',
      transliteration: 'Ar-Raheem',
      meaning: 'The Most Merciful',
      description: 'The One who has plenty of mercy for the believers.',
    ),
    NameOfAllah(
      number: 3,
      arabic: 'الْمَلِكُ',
      transliteration: 'Al-Malik',
      meaning: 'The King',
      description: 'The One with the complete dominion, the One whose dominion is clear from imperfection.',
    ),
    NameOfAllah(
      number: 4,
      arabic: 'الْقُدُّوسُ',
      transliteration: 'Al-Quddus',
      meaning: 'The Most Holy',
      description: 'The One who is pure from any imperfection and clear from children and adversaries.',
    ),
    NameOfAllah(
      number: 5,
      arabic: 'السَّلاَمُ',
      transliteration: 'As-Salam',
      meaning: 'The Source of Peace',
      description: 'The One who is free from every imperfection and deficiency.',
    ),
    NameOfAllah(
      number: 6,
      arabic: 'الْمُؤْمِنُ',
      transliteration: 'Al-Mu\'min',
      meaning: 'The Guardian of Faith',
      description: 'The One who witnessed for Himself that no one is God but Him. And He witnessed for His believers that they are truthful.',
    ),
    NameOfAllah(
      number: 7,
      arabic: 'الْمُهَيْمِنُ',
      transliteration: 'Al-Muhaymin',
      meaning: 'The Protector',
      description: 'The One who witnesses the saying and deeds of His creatures.',
    ),
    NameOfAllah(
      number: 8,
      arabic: 'الْعَزِيزُ',
      transliteration: 'Al-Aziz',
      meaning: 'The Almighty',
      description: 'The Defeater who is never defeated.',
    ),
    NameOfAllah(
      number: 9,
      arabic: 'الْجَبَّارُ',
      transliteration: 'Al-Jabbar',
      meaning: 'The Compeller',
      description: 'The One that nothing happens in His dominion except what He wills.',
    ),
    NameOfAllah(
      number: 10,
      arabic: 'الْمُتَكَبِّرُ',
      transliteration: 'Al-Mutakabbir',
      meaning: 'The Greatest',
      description: 'The One who is clear from the attributes of the creatures and from resembling them.',
    ),
    NameOfAllah(
      number: 11,
      arabic: 'الْخَالِقُ',
      transliteration: 'Al-Khaliq',
      meaning: 'The Creator',
      description: 'The One who brings everything from non-existence to existence.',
    ),
    NameOfAllah(
      number: 12,
      arabic: 'الْبَارِئُ',
      transliteration: 'Al-Bari\'',
      meaning: 'The Originator',
      description: 'The Creator who has the Power to turn the entities.',
    ),
    NameOfAllah(
      number: 13,
      arabic: 'الْمُصَوِّرُ',
      transliteration: 'Al-Musawwir',
      meaning: 'The Fashioner',
      description: 'The One who forms His creatures in different shapes and pictures.',
    ),
    NameOfAllah(
      number: 14,
      arabic: 'الْغَفَّارُ',
      transliteration: 'Al-Ghaffar',
      meaning: 'The Forgiver',
      description: 'The One who forgives a lot.',
    ),
    NameOfAllah(
      number: 15,
      arabic: 'الْقَهَّارُ',
      transliteration: 'Al-Qahhar',
      meaning: 'The Subduer',
      description: 'The Dominant One, the One who has the perfect Power and is not unable over anything.',
    ),
    NameOfAllah(
      number: 16,
      arabic: 'الْوَهَّابُ',
      transliteration: 'Al-Wahhab',
      meaning: 'The Bestower',
      description: 'The One who is Generous in giving plenty without any return.',
    ),
    NameOfAllah(
      number: 17,
      arabic: 'الرَّزَّاقُ',
      transliteration: 'Ar-Razzaq',
      meaning: 'The Provider',
      description: 'The One who gives sustenance to all His creatures.',
    ),
    NameOfAllah(
      number: 18,
      arabic: 'الْفَتَّاحُ',
      transliteration: 'Al-Fattah',
      meaning: 'The Opener',
      description: 'The One who opens for His slaves the closed worldly and religious matters.',
    ),
    NameOfAllah(
      number: 19,
      arabic: 'اَلْعَلِيْمُ',
      transliteration: 'Al-Alim',
      meaning: 'The All-Knowing',
      description: 'The One nothing is absent from His knowledge.',
    ),
    NameOfAllah(
      number: 20,
      arabic: 'الْقَابِضُ',
      transliteration: 'Al-Qabid',
      meaning: 'The Constrictor',
      description: 'The One who constricts the sustenance by His wisdom.',
    ),
    NameOfAllah(
      number: 21,
      arabic: 'الْبَاسِطُ',
      transliteration: 'Al-Basit',
      meaning: 'The Expander',
      description: 'The One who expands and gives abundantly by His generosity and mercy.',
    ),
    NameOfAllah(
      number: 22,
      arabic: 'الْخَافِضُ',
      transliteration: 'Al-Khafid',
      meaning: 'The Abaser',
      description: 'The One who lowers whoever He wills by His destruction.',
    ),
    NameOfAllah(
      number: 23,
      arabic: 'الرَّافِعُ',
      transliteration: 'Ar-Rafi\'',
      meaning: 'The Exalter',
      description: 'The One who raises whoever He wills by His endowment.',
    ),
    NameOfAllah(
      number: 24,
      arabic: 'الْمُعِزُّ',
      transliteration: 'Al-Mu\'izz',
      meaning: 'The Honourer',
      description: 'He gives esteem to whoever He wills.',
    ),
    NameOfAllah(
      number: 25,
      arabic: 'المُذِلُّ',
      transliteration: 'Al-Muzill',
      meaning: 'The Dishonourer',
      description: 'He degrades and abases whoever He wills.',
    ),
    NameOfAllah(
      number: 26,
      arabic: 'السَّمِيعُ',
      transliteration: 'As-Sami\'',
      meaning: 'The All-Hearing',
      description: 'The One who hears all things that are heard by His eternal hearing without an ear.',
    ),
    NameOfAllah(
      number: 27,
      arabic: 'الْبَصِيرُ',
      transliteration: 'Al-Basir',
      meaning: 'The All-Seeing',
      description: 'The One who sees all things that are seen by His eternal sight without a pupil.',
    ),
    NameOfAllah(
      number: 28,
      arabic: 'الْحَكَمُ',
      transliteration: 'Al-Hakam',
      meaning: 'The Judge',
      description: 'He is the Ruler and His judgment is His Word.',
    ),
    NameOfAllah(
      number: 29,
      arabic: 'الْعَدْلُ',
      transliteration: 'Al-Adl',
      meaning: 'The Just',
      description: 'The One who is entitled to do what He does.',
    ),
    NameOfAllah(
      number: 30,
      arabic: 'اللَّطِيفُ',
      transliteration: 'Al-Latif',
      meaning: 'The Subtle One',
      description: 'The One who is kind to His slaves and grants them their needs with gentleness.',
    ),
    NameOfAllah(
      number: 31,
      arabic: 'الْخَبِيرُ',
      transliteration: 'Al-Khabir',
      meaning: 'The All-Aware',
      description: 'The One who knows the truth of things.',
    ),
    NameOfAllah(
      number: 32,
      arabic: 'الْحَلِيمُ',
      transliteration: 'Al-Halim',
      meaning: 'The Forbearing',
      description: 'The One who delays the punishment for those who deserve it.',
    ),
    NameOfAllah(
      number: 33,
      arabic: 'الْعَظِيمُ',
      transliteration: 'Al-Azim',
      meaning: 'The Magnificent',
      description: 'The One deserving the attributes of exaltment, glory, extolment, and purity from all imperfection.',
    ),
    NameOfAllah(
      number: 34,
      arabic: 'الْغَفُورُ',
      transliteration: 'Al-Ghafur',
      meaning: 'The All-Forgiving',
      description: 'The One who forgives a lot.',
    ),
    NameOfAllah(
      number: 35,
      arabic: 'الشَّكُورُ',
      transliteration: 'Ash-Shakur',
      meaning: 'The Appreciative',
      description: 'The One who gives much reward for little obedience.',
    ),
    NameOfAllah(
      number: 36,
      arabic: 'الْعَلِيُّ',
      transliteration: 'Al-Aliyy',
      meaning: 'The Most High',
      description: 'The One who is clear from the attributes of the creatures.',
    ),
    NameOfAllah(
      number: 37,
      arabic: 'الْكَبِيرُ',
      transliteration: 'Al-Kabir',
      meaning: 'The Most Great',
      description: 'The One who is greater than everything in status.',
    ),
    NameOfAllah(
      number: 38,
      arabic: 'الْحَفِيظُ',
      transliteration: 'Al-Hafiz',
      meaning: 'The Preserver',
      description: 'The One who protects whatever and whoever He wills to protect.',
    ),
    NameOfAllah(
      number: 39,
      arabic: 'المُقيِت',
      transliteration: 'Al-Muqit',
      meaning: 'The Sustainer',
      description: 'The One who has the power over everything.',
    ),
    NameOfAllah(
      number: 40,
      arabic: 'الْحسِيبُ',
      transliteration: 'Al-Hasib',
      meaning: 'The Reckoner',
      description: 'The One who gives satisfaction.',
    ),
    NameOfAllah(
      number: 41,
      arabic: 'الْجَلِيلُ',
      transliteration: 'Al-Jalil',
      meaning: 'The Majestic',
      description: 'The One who is attributed with greatness of power and glory of status.',
    ),
    NameOfAllah(
      number: 42,
      arabic: 'الْكَرِيمُ',
      transliteration: 'Al-Karim',
      meaning: 'The Generous',
      description: 'The One who is clear from abjectness.',
    ),
    NameOfAllah(
      number: 43,
      arabic: 'الرَّقِيبُ',
      transliteration: 'Ar-Raqib',
      meaning: 'The Watchful',
      description: 'The One that nothing is absent from Him.',
    ),
    NameOfAllah(
      number: 44,
      arabic: 'الْمُجِيبُ',
      transliteration: 'Al-Mujib',
      meaning: 'The Responsive',
      description: 'The One who answers the one in need if he asks Him.',
    ),
    NameOfAllah(
      number: 45,
      arabic: 'الْوَاسِعُ',
      transliteration: 'Al-Wasi\'',
      meaning: 'The All-Encompassing',
      description: 'The Knowledgeable.',
    ),
    NameOfAllah(
      number: 46,
      arabic: 'الْحَكِيمُ',
      transliteration: 'Al-Hakim',
      meaning: 'The Wise',
      description: 'The One who is correct in His doings.',
    ),
    NameOfAllah(
      number: 47,
      arabic: 'الْوَدُودُ',
      transliteration: 'Al-Wadud',
      meaning: 'The Loving One',
      description: 'The One who loves His believing slaves and His believing slaves love Him.',
    ),
    NameOfAllah(
      number: 48,
      arabic: 'الْمَجِيدُ',
      transliteration: 'Al-Majid',
      meaning: 'The Most Glorious',
      description: 'The One who is Majid.',
    ),
    NameOfAllah(
      number: 49,
      arabic: 'الْبَاعِثُ',
      transliteration: 'Al-Ba\'ith',
      meaning: 'The Resurrector',
      description: 'The One who resurrects for reward and punishment.',
    ),
    NameOfAllah(
      number: 50,
      arabic: 'الشَّهِيدُ',
      transliteration: 'Ash-Shahid',
      meaning: 'The Witness',
      description: 'The One who nothing is absent from Him.',
    ),
    NameOfAllah(
      number: 51,
      arabic: 'الْحَقُّ',
      transliteration: 'Al-Haqq',
      meaning: 'The Truth',
      description: 'The One who truly exists.',
    ),
    NameOfAllah(
      number: 52,
      arabic: 'الْوَكِيلُ',
      transliteration: 'Al-Wakil',
      meaning: 'The Trustee',
      description: 'The One who gives satisfaction and is relied upon.',
    ),
    NameOfAllah(
      number: 53,
      arabic: 'الْقَوِيُّ',
      transliteration: 'Al-Qawiyy',
      meaning: 'The Most Strong',
      description: 'The One with complete power.',
    ),
    NameOfAllah(
      number: 54,
      arabic: 'الْمَتِينُ',
      transliteration: 'Al-Matin',
      meaning: 'The Firm One',
      description: 'The One with extreme power which is uninterrupted.',
    ),
    NameOfAllah(
      number: 55,
      arabic: 'الْوَلِيُّ',
      transliteration: 'Al-Waliyy',
      meaning: 'The Protecting Friend',
      description: 'The Supporter.',
    ),
    NameOfAllah(
      number: 56,
      arabic: 'الْحَمِيدُ',
      transliteration: 'Al-Hamid',
      meaning: 'The Praiseworthy',
      description: 'The praised One who deserves to be praised.',
    ),
    NameOfAllah(
      number: 57,
      arabic: 'الْمُحْصِي',
      transliteration: 'Al-Muhsi',
      meaning: 'The Counter',
      description: 'The One who knows the count of everything even though infinite.',
    ),
    NameOfAllah(
      number: 58,
      arabic: 'الْمُبْدِئُ',
      transliteration: 'Al-Mubdi\'',
      meaning: 'The Originator',
      description: 'The One who started the human being, bringing him into existence.',
    ),
    NameOfAllah(
      number: 59,
      arabic: 'الْمُعِيدُ',
      transliteration: 'Al-Mu\'id',
      meaning: 'The Restorer',
      description: 'The One who brings back the creatures after death.',
    ),
    NameOfAllah(
      number: 60,
      arabic: 'الْمُحْيِي',
      transliteration: 'Al-Muhyi',
      meaning: 'The Giver of Life',
      description: 'The One who took out a living human from semen that does not have a soul.',
    ),
    NameOfAllah(
      number: 61,
      arabic: 'اَلْمُمِيتُ',
      transliteration: 'Al-Mumit',
      meaning: 'The Bringer of Death',
      description: 'The One who renders the living dead.',
    ),
    NameOfAllah(
      number: 62,
      arabic: 'الْحَيُّ',
      transliteration: 'Al-Hayy',
      meaning: 'The Ever Living',
      description: 'The One attributed with a life that is unlike our life and is not that of a combination of soul, flesh, and blood.',
    ),
    NameOfAllah(
      number: 63,
      arabic: 'الْقَيُّومُ',
      transliteration: 'Al-Qayyum',
      meaning: 'The Self-Subsisting',
      description: 'The One who remains and does not end.',
    ),
    NameOfAllah(
      number: 64,
      arabic: 'الْوَاجِدُ',
      transliteration: 'Al-Wajid',
      meaning: 'The Finder',
      description: 'The Rich who is never poor.',
    ),
    NameOfAllah(
      number: 65,
      arabic: 'الْمَاجِدُ',
      transliteration: 'Al-Majid',
      meaning: 'The Noble',
      description: 'The One who is Majid.',
    ),
    NameOfAllah(
      number: 66,
      arabic: 'الْواحِدُ',
      transliteration: 'Al-Wahid',
      meaning: 'The One',
      description: 'The One without a partner.',
    ),
    NameOfAllah(
      number: 67,
      arabic: 'اَلاَحَدُ',
      transliteration: 'Al-Ahad',
      meaning: 'The Unique',
      description: 'The One.',
    ),
    NameOfAllah(
      number: 68,
      arabic: 'الصَّمَدُ',
      transliteration: 'As-Samad',
      meaning: 'The Eternal',
      description: 'The Master who is relied upon in matters and is resorted to in ones needs.',
    ),
    NameOfAllah(
      number: 69,
      arabic: 'الْقَادِرُ',
      transliteration: 'Al-Qadir',
      meaning: 'The Able',
      description: 'The One attributed with power.',
    ),
    NameOfAllah(
      number: 70,
      arabic: 'الْمُقْتَدِرُ',
      transliteration: 'Al-Muqtadir',
      meaning: 'The Powerful',
      description: 'The One with the perfect power that nothing is withheld from Him.',
    ),
    NameOfAllah(
      number: 71,
      arabic: 'الْمُقَدِّمُ',
      transliteration: 'Al-Muqaddim',
      meaning: 'The Expediter',
      description: 'The One who puts things in their right places.',
    ),
    NameOfAllah(
      number: 72,
      arabic: 'الْمُؤَخِّرُ',
      transliteration: 'Al-Mu\'akhkhir',
      meaning: 'The Delayer',
      description: 'The One who delays things and puts them in their right places.',
    ),
    NameOfAllah(
      number: 73,
      arabic: 'الأوَّلُ',
      transliteration: 'Al-Awwal',
      meaning: 'The First',
      description: 'The One whose existence is without a beginning.',
    ),
    NameOfAllah(
      number: 74,
      arabic: 'الآخِرُ',
      transliteration: 'Al-Akhir',
      meaning: 'The Last',
      description: 'The One whose existence is without an end.',
    ),
    NameOfAllah(
      number: 75,
      arabic: 'الظَّاهِرُ',
      transliteration: 'Az-Zahir',
      meaning: 'The Manifest',
      description: 'The One that nothing is above Him and nothing is underneath Him.',
    ),
    NameOfAllah(
      number: 76,
      arabic: 'الْبَاطِنُ',
      transliteration: 'Al-Batin',
      meaning: 'The Hidden',
      description: 'The One that nothing is above Him and nothing is underneath Him.',
    ),
    NameOfAllah(
      number: 77,
      arabic: 'الْوَالِي',
      transliteration: 'Al-Wali',
      meaning: 'The Governor',
      description: 'The One who owns things and manages them.',
    ),
    NameOfAllah(
      number: 78,
      arabic: 'الْمُتَعَالِي',
      transliteration: 'Al-Muta\'ali',
      meaning: 'The Most Exalted',
      description: 'The One who is clear from the attributes of the creation.',
    ),
    NameOfAllah(
      number: 79,
      arabic: 'الْبَرُّ',
      transliteration: 'Al-Barr',
      meaning: 'The Source of Goodness',
      description: 'The One who is kind to His creatures, who covered them with His sustenance.',
    ),
    NameOfAllah(
      number: 80,
      arabic: 'التَّوَابُ',
      transliteration: 'At-Tawwab',
      meaning: 'The Acceptor of Repentance',
      description: 'The One who grants repentance to whoever He wills among His creatures.',
    ),
    NameOfAllah(
      number: 81,
      arabic: 'الْمُنْتَقِمُ',
      transliteration: 'Al-Muntaqim',
      meaning: 'The Avenger',
      description: 'The One who victoriously prevails over His enemies.',
    ),
    NameOfAllah(
      number: 82,
      arabic: 'العَفُوُّ',
      transliteration: 'Al-Afuww',
      meaning: 'The Pardoner',
      description: 'The One with wide forgiveness.',
    ),
    NameOfAllah(
      number: 83,
      arabic: 'الرَّؤُوفُ',
      transliteration: 'Ar-Ra\'uf',
      meaning: 'The Compassionate',
      description: 'The One with extreme mercy.',
    ),
    NameOfAllah(
      number: 84,
      arabic: 'مَالِكُ الْمُلْكِ',
      transliteration: 'Malik-ul-Mulk',
      meaning: 'Owner of Sovereignty',
      description: 'The One who controls the dominion and gives dominion to whoever He wills.',
    ),
    NameOfAllah(
      number: 85,
      arabic: 'ذُوالْجَلاَلِ وَالإكْرَامِ',
      transliteration: 'Dhul-Jalali wal-Ikram',
      meaning: 'Lord of Majesty and Bounty',
      description: 'The One who deserves to be Exalted and not denied.',
    ),
    NameOfAllah(
      number: 86,
      arabic: 'الْمُقْسِطُ',
      transliteration: 'Al-Muqsit',
      meaning: 'The Equitable',
      description: 'The One who is Just in His judgment.',
    ),
    NameOfAllah(
      number: 87,
      arabic: 'الْجَامِعُ',
      transliteration: 'Al-Jami\'',
      meaning: 'The Gatherer',
      description: 'The One who gathers the creatures on a day that there is no doubt about.',
    ),
    NameOfAllah(
      number: 88,
      arabic: 'الْغَنِيُّ',
      transliteration: 'Al-Ghaniyy',
      meaning: 'The Self-Sufficient',
      description: 'The One who does not need the creation.',
    ),
    NameOfAllah(
      number: 89,
      arabic: 'الْمُغْنِي',
      transliteration: 'Al-Mughni',
      meaning: 'The Enricher',
      description: 'The One who satisfies the needs of the creatures.',
    ),
    NameOfAllah(
      number: 90,
      arabic: 'اَلْمَانِعُ',
      transliteration: 'Al-Mani\'',
      meaning: 'The Preventer',
      description: 'The One who withholds.',
    ),
    NameOfAllah(
      number: 91,
      arabic: 'الضَّارَّ',
      transliteration: 'Ad-Darr',
      meaning: 'The Distresser',
      description: 'The One who makes harm reach to whoever He wills.',
    ),
    NameOfAllah(
      number: 92,
      arabic: 'النَّافِعُ',
      transliteration: 'An-Nafi\'',
      meaning: 'The Benefiter',
      description: 'The One who gives benefit to whoever He wills.',
    ),
    NameOfAllah(
      number: 93,
      arabic: 'النُّورُ',
      transliteration: 'An-Nur',
      meaning: 'The Light',
      description: 'The One who is the light of the heavens and earth, illuminating hearts with guidance.',
    ),
    NameOfAllah(
      number: 94,
      arabic: 'الْهَادِي',
      transliteration: 'Al-Hadi',
      meaning: 'The Guide',
      description: 'The One who guides His creation to what is beneficial for them.',
    ),
    NameOfAllah(
      number: 95,
      arabic: 'الْبَدِيعُ',
      transliteration: 'Al-Badi\'',
      meaning: 'The Incomparable',
      description: 'The One who created the creation and formed it without any preceding example.',
    ),
    NameOfAllah(
      number: 96,
      arabic: 'اَلْبَاقِي',
      transliteration: 'Al-Baqi',
      meaning: 'The Everlasting',
      description: 'The One for whom death is impossible.',
    ),
    NameOfAllah(
      number: 97,
      arabic: 'الْوَارِثُ',
      transliteration: 'Al-Warith',
      meaning: 'The Inheritor',
      description: 'The One whose existence remains.',
    ),
    NameOfAllah(
      number: 98,
      arabic: 'الرَّشِيدُ',
      transliteration: 'Ar-Rashid',
      meaning: 'The Guide to the Right Path',
      description: 'The One who directs all affairs with perfect wisdom toward the right path.',
    ),
    NameOfAllah(
      number: 99,
      arabic: 'الصَّبُورُ',
      transliteration: 'As-Sabur',
      meaning: 'The Patient',
      description: 'The One who does not quickly punish the sinners.',
    ),
  ];

  /// Get all 99 names
  List<NameOfAllah> getAllNames() => names;

  /// Get a specific name by number (1-99)
  NameOfAllah getName(int number) {
    return names.firstWhere(
      (n) => n.number == number,
      orElse: () => names.first,
    );
  }

  /// Search names by transliteration or meaning
  List<NameOfAllah> searchNames(String query) {
    if (query.isEmpty) return names;
    final lowerQuery = query.toLowerCase();
    return names.where((name) {
      return name.transliteration.toLowerCase().contains(lowerQuery) ||
          name.meaning.toLowerCase().contains(lowerQuery) ||
          name.arabic.contains(query);
    }).toList();
  }
}
